module.exports = {
  images: {
    domains: [
      'www.nba.com',
      // 'img.bleacherreport.net',
      // 'a3.espncdn.com',
      // 'a1.espncdn.com',
      // 'b.fssta.com',
      // 's.espncdn.com',
      // 'nba.com',
      // 'a.espncdn.com',
      // 'a4.espncdn.com',
      // 'a2.espncdn.com',
      // 'a57.foxsports.com',
      // 'media.bleacherreport.com',
      'cdn.nba.com',
      's.hdnux.com',
      'i.dailymail.co.uk',
      'www.thestar.com',
      'assets.startribune.com',
      'static.reuters.com',
      'sportsbookwire.usatoday.com',
      'twt-thumbs.washtimes.com',
      'bloximages.chicago2.vip.townnews.com',
      'www.washingtonpost.com',
      'images.thestar.com',
      'losangeles.cbslocal.com',
      'static.foxnews.com',
      'images.daznservices.com',
      'i.iheart.com',
      'gamespot1.cbsistatic.com',
      'storage.googleapis.com',
      'www.gannett-cdn.com',
      'cbsnews2.cbsistatic.com',
      'www.chron.com',
      'www.cnet.com',
      's1.ibtimes.com',
      'mondrian.mashable.com',
      'warriorswire.usatoday.com',
      's.france24.com',
      'static-entertainment-eus-s-msn-com.akamaized.net',
      'd.newsweek.com',
      'ichef.bbci.co.uk',
      's.yimg.com',
      'lebronwire.usatoday.com',
      'i.cbc.ca',
      'www.theglobeandmail.com',
      'img-s-msn-com.akamaized.net',
      'therookiewire.usatoday.com',
      'thumbor.forbes.com',
      'boston.cbslocal.com',
      'celticswire.usatoday.com',
      'nypost.com',
      'external-preview.redd.it',
      'bostonglobe-prod.cdn.arcpublishing.com',
      'www.wgmd.com',
      'a1.espncdn.com',
      // 'www.basketball.realgm.com',
      // 'www.foxsports.com',
      // 'www.news.google.com',
      // 'www.spox.com',
    ],
  },
};
